apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rarego-tls
  namespace: rarego
spec:
  secretName: rarego-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - rarego.duckdns.org

